{% set name = "pitot" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pitot-{{ version }}.tar.gz
  sha256: 97247d6b70165b3c05fefbf0ae631cfb13ebba71aa71e287c5c0c5d2b2c9f495

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - numpy >=1.23.0
    - pandas >=1.4.3
    - typing-extensions >=4.3.0
    - pyproj >=3.3.1
    - impunity >=1.0.3

test:
  imports:
    - pitot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pitot/
  summary: Toolbox for aeronautic units and conversions
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - xoolive
    - junzis
