{% set name = "pitot" %}
{% set version = "0.3.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pitot-{{ version }}.tar.gz
  sha256: 97247d6b70165b3c05fefbf0ae631cfb13ebba71aa71e287c5c0c5d2b2c9f495

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.2
    - pandas >=2.2.3
    - typing-extensions >=4.12.2
    - pyproj >=3.7.0
    - impunity >=1.0.5

test:
  imports:
    - pitot
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/pitot/
  summary: Toolbox for aeronautic units and conversions
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - xoolive
